### ISSUE TITLE
Artwork

### ISSUE THREAD

**Issue by e7p** [das-labor/badge-2021#4]
Every great badge needs some awesome artwork. I'd really like to volunteer in taking an art draft and putting it into the PCB-shape. Thus, I could also do all the routing stuff basically. Concluding, push here in case any great PCB-art ideas arise and / or the schematic is done. :)

E.g.: What about the style of the logo of @das-labor?

**Comment by orangecms** [comment]
We'd love to have the event artwork \o/
Do you have already for vectorization?

**Comment by e7p** [comment]
So basically it is not clear when / who makes the event artwork now. I also offered help in vectorization there, however the last information was that they would do it themselves. I'll ask again about the current state of the official event logo now.

Edit: Additionally any design ideas (input) like general PCB shape, requirements,... into some draft would be very welcome.

**Comment by orangecms** [comment]
Please have a look at the sketch in the README:
https://github.com/das-labor/badge-2021#sketch

That is quite close to the shape of a famous handheld pocket gaming device. :-)

We just made some progress with the schematics yesterday and withe the prototype.
Check this out: https://twitter.com/OrangeCMS/status/1395852445847334912?s=19 :-)

**Comment by e7p** [comment]
Yes, I already saw the general sketch, not yielding much real artwork ideas though. But no problems. Which famous pocket gaming device? I cannot recall any Gameboy having two joysticks on the bottom...

**Comment by orangecms** [comment]
> Yes, I already saw the general sketch, not yielding much real artwork ideas though. But no problems. Which famous pocket gaming device? I cannot recall any Gameboy having two joysticks on the bottom...

Sorry, I just meant the board dimensions. They are close to a GameBoy Pocket. Can you help me understand what is missing for you? Maybe elaborate on "general PCB shape", I thought you meant the dimensions and basic outline, like what the sketch is showing. 🤔

**Comment by e7p** [comment]
Well, the most important detail I somehow missed was, that the sketch in the README already showed the desired form factor. Otherwise I would have guessed that the badge might be also in the format similar to the event logo. Badges like these do exist. However, if only a simple form is wished, no problem.

Other things that are missing for now:
* final schematic
* vectorized event logo (still no response... I'll ask again)

So, not too much missing until we're getting more creative :eggplant:

**Comment by e7p** [comment]
Making progress with the vectorization of the event logo / design. Will look great on the badge, promise :smile:

**Comment by e7p** [comment]
Umm, when again will the final PCBs be ordered? I think it was end of August. I might find some time for integrating the logo next week, hope this is sufficient.

**Comment by orangecms** [comment]
If you look at the current board, you should see the logo already baked in; @arnobert just did that before ordering rev 1. You should find some rev 1 boards floating around, they've arrived already. :)

And sorry, I totally forgot to write that here... could you maybe check if there's any adjustments you'd like to do? 🙏

**Comment by orangecms** [comment]
closing now since we made the final order and the job is done 🥳
